# Spring相关配置
spring:
  # Profile配置
  profiles:
    # 激活哪些Profile配置
    active: dev
  # jackson框架的相关配置
  jackson:
    # 服务器端响应JSON结果时，JSON结果中默认包含哪些属性
    default-property-inclusion: non_null

# Mybatis相关配置
mybatis:
  # 配置SQL语句的XML文件所在的位置
  mapper-locations: classpath:mapper/*.xml

# Knife4j配置
knife4j:
  # 开启增强模式
  enable: true
